# Generated by Django 4.1.9 on 2023-05-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_edu_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Learner',
            new_name='Student',
        ),
    ]
