# Generated by Django 4.1.9 on 2023-05-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSummary',
        ),
    ]
