# Generated by Django 4.1.9 on 2023-05-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_coursesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Course Summary',
                'verbose_name_plural': 'Courses Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
    ]
