# Generated by Django 3.0.5 on 2021-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('chairman_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('attiregroup', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('sdate', models.DateField(auto_now=True)),
                ('edate', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]