# Generated by Django 3.0.5 on 2021-02-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('admin', '0002_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='request_by_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
